// export const GRAPHQL_DEV_CLIENT = "http://auth-dev.ap-south-1.elasticbeanstalk.com/graphql"
// export const API_URL = "http://auth-dev.ap-south-1.elasticbeanstalk.com"
export const BASE_URL = "https://api-beta.stylori.com/"
export const API_URL = "https://api-beta.stylori.com"
export const GRAPHQL_DEV_CLIENT = "https://api-beta.stylori.com/graphql"
// export const GRAPHQL_DEV_CLIENT = "http://192.168.1.105:8000/graphql"
